### ISSUE TITLE
Make the `wrapper` a `std::ranges::view`

### ISSUE THREAD

**Issue by Minimonium** [hipony/enumerate#34]

**Comment by uselessgoddess** [comment]
You can use something like that [WARNING C++20]:
```cpp
template<std::ranges::range Range>
struct wrapper_view
{
    using value_type = std::ranges::range_value_t<Range>;
    using iterator = wrapper_iterator<value_type>;

    value_type** _data;
    int  _size;

    wrapper_view(Range& range)
    {
        _size = std::ranges::size(range); // warning: forward_list not have size(). Use iterators arithmetic 
        _data = new value_type*[_size];

        for (auto&& [i, value] : hipony::enumerate(range)) {
            _data[i] = &value;
        }
    }
    
    auto begin() { return iterator {0, _data}; }
    auto end() { return iterator {_size, _data + _size}; }
};
```
Where the wrapper_iterator looks like this:
```cpp
template<typename Value>
struct wrapper_iterator
{
    using iterator_category = std::random_access_iterator_tag;

    struct view { size_type index; Value& value; }; // can use your struct

    size_type index;
    Value** pointer;

    auto operator*() const { return view {index, **pointer}; }
    
    // other random access iterator operators
};
```
**With this, any container can be arranged in memory in order. And can use any `std::ranges` algorithms**
For example:
```cpp
auto string = std::string{ "3i like cocks and chicken12" };

namespace views = std::views;
for (auto [index, value] : wrapper_view(string)
                         | views::reverse
                         | views::drop(2)
                         | views::take(10)
                      // | views::split(' ') # not work. compare iter_value
                         | views::drop_while([](auto&& item) { return item.value % 2 == 0; }) // create special function)
{
    std::cout << index << ": " << value << std::endl;
}
```

You can also use my library [OH NO. IS NOT PR]. And easy parody the syntax `ranges adaptors`
```cpp
constexpr universal_adaptor wrap = [] <std::ranges::range Range>(Range&& range)
{
    return wrapper_view<Range>{range};
}
........
for (auto [index, value] : array | wrap | views::reverse)
{
      .......
}
```

**Comment by Minimonium** [comment]
```cpp
new value_type*[_size];
```
I'd like to avoid any need for allocators in the design to keep it fast and simple. 

For now, I'm planning a `reference_wrapper`-based view.

**Comment by uselessgoddess** [comment]
Yes, it definitely makes sense. Everyone loves **modern C++**

**Comment by Minimonium** [comment]
The issue is not exactly the "modern C++" issue, but a good API design would require to expose allocation customization which is the same in even C.

**Comment by Minimonium** [comment]
I was forced to use a pointer instead of a reference_wrapper because right now MSVC implements an outdated ranges specification for the view concept, which requires default constructible. The new concept doesn't need it. 

There still icky things about the lack of concept/ranges support with Clang which trips Clang+libstdc++ builds and also I'm pretty sure iterator tag propagation is broken for ranges. The iterator implementation doesn't support all the operations so it may in fact lie about the iterator tag which may trip some range algorithms, needs investigation.
